// Participant feedback page, shown at the end of the sub-batteries whose score
// can be computed in the browser: Rhythm (BAT and tapping), Perception (MBEMA),
// Emotion 1 (SMART) and Movement. Each score is shown as 3 to 5 stars from its
// quartile among everyone tested so far (utils/feedbackNorms.js, generated by
// analyses/reports/scripts/make_feedback_norms.py). Singing and Emotion 2 get no
// feedback yet.
//
// The scores below must stay identical to the pipeline's, otherwise the dot and
// the curve are on different scales:
//   BAT       feature_extraction/bat/features.py     mean(8 - offset), training dropped
//   MBEMA     processBatteries/mbema.py              proportion correct per part
//   SMART     processBatteries/emotion_adaptive.py   Theta of the last trial
//   tapping   Variability per trial (featureExtraction.js), mean over trials
//   movement  PeriodConf per trial (featureExtraction.js), mean over trials
//
// Needs: feedbackNorms.js, translations.js (feedbackT, buttons); for tapping and
// movement also featureExtraction.js and feedbackAnnotations.js.

var FEEDBACK_DECIMALS = 4  // same rounding as make_feedback_norms.py

// ─── switch ──────────────────────────────────────────────────────────────────
// Feedback is off unless the battery URL has feedback=true (any case). Rhythm
// and Movement pass it on across their page reloads with feedbackUrlParam().
function feedbackEnabled(){
  try {
    return String(jatos.urlQueryParameters.feedback).toLowerCase() === "true"
  } catch(e) {
    return false
  }
}

function feedbackUrlParam(){
  return feedbackEnabled() ? "&feedback=true" : ""
}

// ─── storage across page loads ───────────────────────────────────────────────
// Rhythm reloads the page between trials, so BAT offsets are kept in
// localStorage until the last excerpt. Failing storage only means no feedback.
var feedbackStore = {
  key: function(task, userID){ return "mmbbFeedback_" + task + "_" + userID },
  get: function(task, userID){
    try { return JSON.parse(localStorage.getItem(this.key(task, userID))) || {} }
    catch(e) { return {} }
  },
  put: function(task, userID, field, value){
    try {
      var stored = this.get(task, userID)
      stored[field] = value
      localStorage.setItem(this.key(task, userID), JSON.stringify(stored))
    } catch(e) {}
  },
  clear: function(task, userID){
    try { localStorage.removeItem(this.key(task, userID)) } catch(e) {}
  }
}

// ─── scores ──────────────────────────────────────────────────────────────────
// offsets: {batSong: final offset}, as stored by bat.js.
function feedbackScoreBAT(offsets){
  var scores = Object.keys(offsets)
    .filter(song => song.indexOf("training") === -1)
    .map(song => 8 - Number(offsets[song]))
    .filter(s => !isNaN(s))
  if(scores.length == 0){ return null }
  return { score: scores.reduce((a, b) => a + b, 0) / scores.length, nItems: scores.length }
}

// Answer keys for items 1..20 in presentation order (= processBatteries/mbema.py).
// 0 = same / heard before, 1 = different / new; the logged response is the
// button index on the same scale.
var feedbackMBEMAKeys = {
  Melody: [1,0,1,1,1,0,1,0,0,0,1,0,1,0,1,0,1,0,0,1],
  Rhythm: [1,0,0,1,1,0,1,1,0,1,0,1,0,0,1,0,0,1,0,1],
  Memory: [1,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,1,0,0]
}

// trials: jsPsych.data.get().values(). Each test item is an audio trial whose
// answer is the next trial's response; practice items ("Example n") don't match.
function feedbackScoreMBEMA(trials){
  var out = {}
  for(var i = 0; i < trials.length - 1; i++){
    var m = String(trials[i].stimulus).match(/b(Melody|Rhythm|Memory) - (\d+)\.wav$/)
    var response = trials[i + 1].response
    if(!m || response === null || response === undefined){ continue }
    var part = m[1], key = feedbackMBEMAKeys[part][Number(m[2]) - 1]
    if(key === undefined){ continue }
    out[part] = out[part] || { correct: 0, nItems: 0 }
    out[part].nItems += 1
    out[part].correct += Number(Number(response) === key)
  }
  Object.keys(out).forEach(p => out[p].score = out[p].correct / out[p].nItems)
  return out
}

// trials: jsPsych.data.get().values(); the adaptive trials carry part = "one".
function feedbackScoreSMART(trials){
  var adaptive = trials.filter(t => t.part === "one" && typeof t.Theta === "number")
  if(adaptive.length == 0){ return null }
  return { score: adaptive[adaptive.length - 1].Theta, nItems: adaptive.length }
}

// A score on the scale the norm is drawn on (tapping Variability: log)
function feedbackScale(norm, score){
  return norm.transform === "log" ? Math.log(score) : score
}

// Share of the reference sample scoring the same or worse, in %.
function feedbackPercentile(norm, score){
  var s = Number(feedbackScale(norm, score).toFixed(FEEDBACK_DECIMALS)), sameOrWorse = 0
  norm.freq.forEach(vc => {
    if(norm.lowerIsBetter ? vc[0] >= s - 1e-9 : vc[0] <= s + 1e-9){ sameOrWorse += vc[1] }
  })
  return Math.round(100 * sameOrWorse / norm.n)
}

// ─── stars ───────────────────────────────────────────────────────────────────
// Everyone gets 3 stars. The other two are four half-stars, one per quartile
// reached: bottom quarter 3.5, second 4, third 4.5, top quarter 5. The quartile
// comes from the share of the reference sample scoring the same or worse.
function feedbackStars(norm, score){
  var quartile = Math.min(4, Math.max(1, Math.ceil(feedbackPercentile(norm, score) / 25)))
  return 3 + 0.5 * quartile
}

// Five stars, filled up to `stars` (a multiple of 0.5)
function feedbackStarsSVG(stars, lang){
  var pts = "12,1.5 15.1,8.3 22.5,9.1 17,14.1 18.5,21.4 12,17.7 5.5,21.4 7,14.1 1.5,9.1 8.9,8.3"
  var html = ""
  for(var i = 0; i < 5; i++){
    var fill = Math.max(0, Math.min(1, stars - i))           // 1, 0.5 or 0
    var id = "feedbackHalf" + Math.random().toString(36).slice(2)
    html += '<svg class="feedbackStar" viewBox="0 0 24 23" aria-hidden="true">' +
              '<defs><clipPath id="' + id + '"><rect x="0" y="0" width="' + (24 * fill) + '" height="23"/></clipPath></defs>' +
              '<polygon points="' + pts + '" fill="#e2e2e2"/>' +
              (fill > 0 ? '<polygon points="' + pts + '" fill="#fa6400" clip-path="url(#' + id + ')"/>' : '') +
            '</svg>'
  }
  var label = feedbackT["starsLabel"][lang].replace("{s}", lang == "fi" ? String(stars).replace(".", ",") : String(stars))
  return '<div class="feedbackStars" role="img" aria-label="' + label + '">' + html + '</div>'
}

// ─── page ───────────────────────────────────────────────────────────────────
// The page is NOT a jsPsych trial: it is shown after jsPsych has finished and
// the battery has saved its data, so the results are exactly what they were
// without feedback (no extra row, no shifted trial_index).
// sections: [{title, norm, score, detail}]
function feedbackPageHTML(lang, sections){
  var html = sections.map(s => {
    return '<div class="feedbackSection">' +
             (s.title ? '<div class="feedbackTitle">' + s.title + '</div>' : '') +
             feedbackStarsSVG(feedbackStars(s.norm, s.score), lang) +
             (s.detail ? '<div class="feedbackText">' + s.detail + '</div>' : '') +
           '</div>'
  }).join("")
  return '<div class="feedbackPage">' +
           '<div class="feedbackHeading">' + feedbackT["heading"][lang] + '</div>' +
           '<div class="feedbackText">' + feedbackT["starsExplain"][lang] + '</div>' +
           html +
           '<div class="feedbackNote">' + feedbackT["note"][lang] + '</div>' +
           '<button class="jspsych-btn" id="feedbackContinue">' + buttons["continue"][lang] + '</button>' +
         '</div>'
}

// Shows the page, then calls onContinue. Without feedback=true, without a score
// or on any error it calls onContinue straight away, so the redirect never
// depends on feedback.
function showFeedbackPage(lang, getSections, onContinue){
  if(!feedbackEnabled()){ onContinue(); return }
  var sections = []
  try {
    sections = getSections().filter(s => s && s.norm && typeof s.score === "number" && isFinite(s.score))
  } catch(e) {
    console.log("Feedback not shown:", e)
  }
  if(sections.length == 0){ onContinue(); return }
  try {
    var wrapper = document.createElement("div")
    wrapper.className = "feedbackOverlay"
    wrapper.innerHTML = feedbackPageHTML(lang, sections)
    document.body.appendChild(wrapper)
    window.scrollTo(0, 0)
    var done = false
    document.getElementById("feedbackContinue").addEventListener("click", function(){
      if(done){ return }
      done = true
      this.disabled = true
      onContinue()
    })
  } catch(e) {
    console.log("Feedback not shown:", e)
    onContinue()
  }
}

// ─── per-battery sections ────────────────────────────────────────────────────
function batFeedbackSections(lang, userID){
  var r = feedbackScoreBAT(feedbackStore.get("bat", userID))
  if(r == null){ return [] }
  return [{ norm: feedbackNorms["bat"], score: r.score,
            title: feedbackT["batTitle"][lang] }]
}

// trials: jsPsych.data.get().values()
function mbemaFeedbackSections(lang, trials){
  var r = feedbackScoreMBEMA(trials)
  return ["Melody", "Rhythm", "Memory"].filter(p => r[p]).map(p => ({
    norm: feedbackNorms["mbema_" + p], score: r[p].score,
    title: feedbackT["mbema" + p][lang]
  }))
}

function smartFeedbackSections(lang, trials){
  var r = feedbackScoreSMART(trials)
  if(r == null){ return [] }
  return [{ norm: feedbackNorms["smart"], score: r.score,
            title: feedbackT["smartTitle"][lang] }]
}

// ─── tapping and movement ────────────────────────────────────────────────────
// Rhythm and Movement reload the page between trials, so each trial's score is
// stored (by stimulus) when the trial ends. The trial's data are only read.
// Any failure here only means no feedback; it never touches the task.
function feedbackRecordTapTrial(userID, data){
  if(!feedbackEnabled()){ return }
  try {
    var v = tapTrialVariability(data.rt, data.stimulus, feedbackAnnotations)
    if(v !== null){ feedbackStore.put("tap", userID, featureStimulusKey(data.stimulus), v) }
  } catch(e) { console.log("Tapping feedback score not computed:", e) }
}

function feedbackRecordMovementTrial(userID, data){
  if(!feedbackEnabled()){ return }
  try {
    var v = movementTrialPeriodConf(data.accelerometer_data, data.stimulus, feedbackAnnotations)
    if(v !== null){ feedbackStore.put("movement", userID, featureStimulusKey(data.stimulus), v) }
  } catch(e) { console.log("Movement feedback score not computed:", e) }
}

// Participant score = mean over the trials that have one (the pipeline averages
// over metronome and music for tapping, metronome and two free dances for movement)
function feedbackStoredMean(task, userID){
  var v = Object.values(feedbackStore.get(task, userID)).map(Number).filter(isFinite)
  return v.length ? v.reduce((a, b) => a + b, 0) / v.length : null
}

function tapFeedbackSections(lang, userID){
  var score = feedbackStoredMean("tap", userID)
  if(score === null || !(score > 0)){ return [] }
  return [{ norm: feedbackNorms["tap_variability"], score: score,
            title: feedbackT["tapTitle"][lang], detail: feedbackT["tapDetail"][lang] }]
}

function movementFeedbackSections(lang, userID){
  var score = feedbackStoredMean("movement", userID)
  if(score === null){ return [] }
  return [{ norm: feedbackNorms["movement_period_conf"], score: score,
            title: feedbackT["movementTitle"][lang], detail: feedbackT["movementDetail"][lang] }]
}
