// Participant feedback page, shown at the end of the sub-batteries whose score
// can be computed in the browser: BAT (Rhythm), MBEMA (Perception) and
// Emotion 1 (SMART). Each score is drawn as a dot on a Gaussian with the mean and
// SD of everyone tested so far (utils/feedbackNorms.js, generated by
// analyses/reports/scripts/make_feedback_norms.py). Singing, movement, tapping and
// Emotion 2 get no feedback yet.
//
// The scores below must stay identical to the pipeline's, otherwise the dot and
// the curve are on different scales:
//   BAT    feature_extraction/bat/features.py      mean(8 - offset), training dropped
//   MBEMA  processBatteries/mbema.py               proportion correct per part
//   SMART  processBatteries/emotion_adaptive.py    Theta of the last trial
//
// Needs: feedbackNorms.js, translations.js (feedbackT, buttons).

var FEEDBACK_DECIMALS = 4  // same rounding as make_feedback_norms.py

// ─── storage across page loads ───────────────────────────────────────────────
// Rhythm reloads the page between trials, so BAT offsets are kept in
// localStorage until the last excerpt. Failing storage only means no feedback.
var feedbackStore = {
  key: function(task, userID){ return "mmbbFeedback_" + task + "_" + userID },
  get: function(task, userID){
    try { return JSON.parse(localStorage.getItem(this.key(task, userID))) || {} }
    catch(e) { return {} }
  },
  put: function(task, userID, field, value){
    try {
      var stored = this.get(task, userID)
      stored[field] = value
      localStorage.setItem(this.key(task, userID), JSON.stringify(stored))
    } catch(e) {}
  },
  clear: function(task, userID){
    try { localStorage.removeItem(this.key(task, userID)) } catch(e) {}
  }
}

// ─── scores ──────────────────────────────────────────────────────────────────
// offsets: {batSong: final offset}, as stored by bat.js.
function feedbackScoreBAT(offsets){
  var scores = Object.keys(offsets)
    .filter(song => song.indexOf("training") === -1)
    .map(song => 8 - Number(offsets[song]))
    .filter(s => !isNaN(s))
  if(scores.length == 0){ return null }
  return { score: scores.reduce((a, b) => a + b, 0) / scores.length, nItems: scores.length }
}

// Answer keys for items 1..20 in presentation order (= processBatteries/mbema.py).
// 0 = same / heard before, 1 = different / new; the logged response is the
// button index on the same scale.
var feedbackMBEMAKeys = {
  Melody: [1,0,1,1,1,0,1,0,0,0,1,0,1,0,1,0,1,0,0,1],
  Rhythm: [1,0,0,1,1,0,1,1,0,1,0,1,0,0,1,0,0,1,0,1],
  Memory: [1,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,1,0,0]
}

// trials: jsPsych.data.get().values(). Each test item is an audio trial whose
// answer is the next trial's response; practice items ("Example n") don't match.
function feedbackScoreMBEMA(trials){
  var out = {}
  for(var i = 0; i < trials.length - 1; i++){
    var m = String(trials[i].stimulus).match(/b(Melody|Rhythm|Memory) - (\d+)\.wav$/)
    var response = trials[i + 1].response
    if(!m || response === null || response === undefined){ continue }
    var part = m[1], key = feedbackMBEMAKeys[part][Number(m[2]) - 1]
    if(key === undefined){ continue }
    out[part] = out[part] || { correct: 0, nItems: 0 }
    out[part].nItems += 1
    out[part].correct += Number(Number(response) === key)
  }
  Object.keys(out).forEach(p => out[p].score = out[p].correct / out[p].nItems)
  return out
}

// trials: jsPsych.data.get().values(); the adaptive trials carry part = "one".
function feedbackScoreSMART(trials){
  var adaptive = trials.filter(t => t.part === "one" && typeof t.Theta === "number")
  if(adaptive.length == 0){ return null }
  return { score: adaptive[adaptive.length - 1].Theta, nItems: adaptive.length }
}

// Share of the reference sample scoring the same or lower, in %.
function feedbackPercentile(norm, score){
  var s = Number(score.toFixed(FEEDBACK_DECIMALS)), atOrBelow = 0
  norm.freq.forEach(vc => { if(vc[0] <= s + 1e-9){ atOrBelow += vc[1] } })
  return Math.round(100 * atOrBelow / norm.n)
}

// ─── drawing ─────────────────────────────────────────────────────────────────
// Gaussian (norm.mean, norm.sd) over norm.range with the participant as a dot.
// lowLabel / highLabel name the ends of the x axis.
function feedbackCurveSVG(norm, score, lowLabel, highLabel, lang){
  var W = 320, H = 150, padX = 16, top = 26, base = 112
  var lo = norm.range[0], hi = norm.range[1]
  var clamp = v => Math.min(hi, Math.max(lo, v))
  var x = v => padX + (clamp(v) - lo) / (hi - lo) * (W - 2 * padX)
  var pdf = v => Math.exp(-0.5 * Math.pow((v - norm.mean) / norm.sd, 2))
  var y = v => base - pdf(v) * (base - top)

  var pts = []
  for(var i = 0; i <= 120; i++){
    var v = lo + (hi - lo) * i / 120
    pts.push(x(v).toFixed(1) + "," + y(v).toFixed(1))
  }
  var curve = "M" + pts.join(" L")
  var area = curve + " L" + x(hi).toFixed(1) + "," + base + " L" + x(lo).toFixed(1) + "," + base + " Z"

  var px = x(score), py = y(clamp(score))
  var mx = x(norm.mean)
  // keep the "You" label inside the drawing near the edges
  var anchor = px < 40 ? "start" : (px > W - 40 ? "end" : "middle")

  return '<svg class="feedbackCurve" viewBox="0 0 ' + W + ' ' + H + '" role="img" ' +
           'aria-label="' + feedbackT["youAreHere"][lang] + '">' +
         '<path d="' + area + '" fill="rgba(250,100,0,0.15)"/>' +
         '<path d="' + curve + '" fill="none" stroke="#fa6400" stroke-width="2"/>' +
         '<line x1="' + padX + '" y1="' + base + '" x2="' + (W - padX) + '" y2="' + base + '" stroke="#555" stroke-width="1"/>' +
         '<line x1="' + mx + '" y1="' + y(norm.mean) + '" x2="' + mx + '" y2="' + base + '" stroke="#555" stroke-width="1" stroke-dasharray="3 3"/>' +
         '<text x="' + mx + '" y="' + (base + 14) + '" font-size="10" fill="#555" text-anchor="middle">' + feedbackT["average"][lang] + '</text>' +
         '<text x="' + padX + '" y="' + (base + 30) + '" font-size="10" fill="#555" text-anchor="start">' + lowLabel + '</text>' +
         '<text x="' + (W - padX) + '" y="' + (base + 30) + '" font-size="10" fill="#555" text-anchor="end">' + highLabel + '</text>' +
         '<line x1="' + px + '" y1="' + py + '" x2="' + px + '" y2="' + base + '" stroke="purple" stroke-width="2"/>' +
         '<circle cx="' + px + '" cy="' + py + '" r="7" fill="purple" stroke="#fff" stroke-width="2"/>' +
         '<text x="' + px + '" y="' + (py - 12) + '" font-size="12" font-weight="bold" fill="purple" stroke="#fff" stroke-width="3" paint-order="stroke" text-anchor="' + anchor + '">' + feedbackT["you"][lang] + '</text>' +
         '</svg>'
}

// ─── page ───────────────────────────────────────────────────────────────────
// The page is NOT a jsPsych trial: it is shown after jsPsych has finished and
// the battery has saved its data, so the results are exactly what they were
// without feedback (no extra row, no shifted trial_index).
// sections: [{title, norm, score, detail, lowLabel, highLabel}]
function feedbackPageHTML(lang, sections){
  var html = sections.map(s => {
    var pct = feedbackPercentile(s.norm, s.score)
    return '<div class="feedbackSection">' +
             (s.title ? '<div class="feedbackTitle">' + s.title + '</div>' : '') +
             feedbackCurveSVG(s.norm, s.score, s.lowLabel, s.highLabel, lang) +
             '<div class="feedbackText">' + (s.detail ? s.detail + '<br>' : '') +
               feedbackT["percentile"][lang].replace("{p}", pct).replace("{n}", s.norm.n) +
             '</div>' +
           '</div>'
  }).join("")
  return '<div class="feedbackPage">' +
           '<div class="feedbackHeading">' + feedbackT["heading"][lang] + '</div>' +
           html +
           '<div class="feedbackNote">' + feedbackT["note"][lang] + '</div>' +
           '<button class="jspsych-btn" id="feedbackContinue">' + buttons["continue"][lang] + '</button>' +
         '</div>'
}

// Shows the page, then calls onContinue. Without a score (or on any error) it
// calls onContinue straight away, so the redirect never depends on feedback.
function showFeedbackPage(lang, getSections, onContinue){
  var sections = []
  try {
    sections = getSections().filter(s => s && s.norm && typeof s.score === "number" && isFinite(s.score))
  } catch(e) {
    console.log("Feedback not shown:", e)
  }
  if(sections.length == 0){ onContinue(); return }
  try {
    var wrapper = document.createElement("div")
    wrapper.className = "feedbackOverlay"
    wrapper.innerHTML = feedbackPageHTML(lang, sections)
    document.body.appendChild(wrapper)
    window.scrollTo(0, 0)
    var done = false
    document.getElementById("feedbackContinue").addEventListener("click", function(){
      if(done){ return }
      done = true
      this.disabled = true
      onContinue()
    })
  } catch(e) {
    console.log("Feedback not shown:", e)
    onContinue()
  }
}

// ─── per-battery sections ────────────────────────────────────────────────────
function batFeedbackSections(lang, userID){
  var r = feedbackScoreBAT(feedbackStore.get("bat", userID))
  if(r == null){ return [] }
  return [{ norm: feedbackNorms["bat"], score: r.score,
            title: feedbackT["batTitle"][lang],
            lowLabel: feedbackT["lower"][lang], highLabel: feedbackT["higher"][lang] }]
}

// trials: jsPsych.data.get().values()
function mbemaFeedbackSections(lang, trials){
  var r = feedbackScoreMBEMA(trials)
  return ["Melody", "Rhythm", "Memory"].filter(p => r[p]).map(p => ({
    norm: feedbackNorms["mbema_" + p], score: r[p].score,
    title: feedbackT["mbema" + p][lang],
    detail: feedbackT["nCorrect"][lang].replace("{k}", r[p].correct).replace("{n}", r[p].nItems),
    lowLabel: "0 %", highLabel: "100 %"
  }))
}

function smartFeedbackSections(lang, trials){
  var r = feedbackScoreSMART(trials)
  if(r == null){ return [] }
  return [{ norm: feedbackNorms["smart"], score: r.score,
            title: feedbackT["smartTitle"][lang],
            lowLabel: feedbackT["lower"][lang], highLabel: feedbackT["higher"][lang] }]
}
